name: wifi_manager_flutter
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1


environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  wifi_manager:
    git:
      url: https://github.com/jbrenorv/wifi-manager
      ref: 658ebc217947af4af8ee2203dad6f1b2cbeddc4f

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
